# Generated by Django 3.1.3 on 2021-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210125_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pub_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
